
export default class EvotorService {
    // https://api.evotorservice.ru/user/01-000000000738894/stores/a06c4306-732d-4914-9543-a588af06c683
    //_apiBase = 'https://api.evotorservice.ru';
    _apiEvotorBase = 'https://api.evotor.ru/api/v1';
    _apiServiceBase = 'https://api.evotorservice.ru';
    state = {
        userId: '01-000000000738894',
        token: 'a06c4306-732d-4914-9543-a588af06c683',
        stores: [
            {"uuid":  "20180507-447F-40C1-8081-52D4B03CD7AB"}
        ],
        data: [
                {
                    "uuid": "011845e5-d2f3-433e-a961-dcdbd4e6927b",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Адаптер DVI-D to HDMI Exegate 25M\/19F",
                    "code": "86",
                    "barCodes": [
                        "4897040852920"
                    ],
                    "price": 150,
                    "costPrice": 87,
                    "quantity": 3,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": null,
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "2d852d4f-48c2-4db3-b27d-f9be610a3408",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Адаптер для установки SSD\/HDD 2.5\" в отсек DVD, 12.6mm",
                    "code": "116",
                    "barCodes": [],
                    "price": 400,
                    "costPrice": 250,
                    "quantity": 3,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": null,
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "900e9658-02fc-4c40-be60-093683c72a15",
                    "group": false,
                    "hasVariants": null,
                    "type": "NORMAL",
                    "name": "SvetoCopy Бумага офисная А4 500л",
                    "code": "5",
                    "barCodes": [
                        "4605817132102",
                        "4605817132119"
                    ],
                    "price": 260,
                    "costPrice": 232,
                    "quantity": 43,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": null,
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "1194fc78-50dd-4d93-a2cb-11f8b93418e9",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Антивирус Dr.Web Security Space 3 ПК 1 год",
                    "code": "101",
                    "barCodes": [
                        "4607141351297"
                    ],
                    "price": 1500,
                    "costPrice": 1150,
                    "quantity": 3,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": null,
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "7442d67b-dd94-49f6-a2a4-8bbc0a63b15d",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Барабан Content для Samsung ML-1210\/1250\/4500\/Xerox 3110",
                    "code": "537",
                    "barCodes": [
                        "2000000000268"
                    ],
                    "price": 350,
                    "costPrice": 250,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "192416",
                    "parentUuid": null,
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "8cc62770-fea1-4f5e-a2cc-f3eeaf727d97",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Барабан Content для HP 1005\/1006\/1505\/1102",
                    "code": "538",
                    "barCodes": [
                        "4690665027182",
                        "V0032548"
                    ],
                    "price": 200,
                    "costPrice": 85.52,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": null,
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "90dd1bd3-947f-4668-8bb0-e43ecef87470",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Барабан Content для HP Color LJ Pro M252\/277\/452\/477\/M154A",
                    "code": "546",
                    "barCodes": [
                        "V0034046"
                    ],
                    "price": 300,
                    "costPrice": 147.36,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": null,
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Компьютерные комплектующие",
                    "code": "604",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": null,
                    "description": null,
                    "articleNumber": null,
                    "parentUuid": null,
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "72856675-1826-48b8-bbe5-d7aa788e722f",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Материнские платы",
                    "code": "594",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": null,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "e8d08c80-2c51-4cc5-b25f-a2f993a0079f",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Корпуса",
                    "code": "600",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": null,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "e3a235a3-aeaf-4bdc-86dd-7cecb2395daf",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Видеокарты",
                    "code": "595",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": null,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "5aee69ad-1670-4fa5-a103-9a79171a7032",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Накопители",
                    "code": "598",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": null,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "a47216aa-f058-40ef-9725-9eea7fd99bc1",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Блоки питания",
                    "code": "599",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": null,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "822455cf-20a1-42ec-ad9d-4c548f1cc08f",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Процессоры",
                    "code": "593",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": null,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "3f14d222-afbc-4676-9b57-b79c1c52e82d",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Звуковые карты",
                    "code": "602",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": null,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "bc2c289d-d71b-4021-9df1-bdf11b0b0ca5",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Программное обеспечение",
                    "code": "606",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": null,
                    "description": null,
                    "articleNumber": null,
                    "parentUuid": null,
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "f8c2581b-d146-4885-9aee-681e4d3614b7",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Оперативная память",
                    "code": "596",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "0a4d7614-5480-4d7b-9ed2-705d8e03f8b6",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Системы охлаждения",
                    "code": "597",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "cc6215ca-b114-448e-96be-9568dca27301",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Приводы",
                    "code": "601",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "b881b484-85c3-4770-a158-4d0bc06cd417",
                    "group": true,
                    "hasVariants": false,
                    "type": null,
                    "name": "Кабели",
                    "code": "603",
                    "barCodes": null,
                    "price": null,
                    "costPrice": null,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": null,
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "d2d438dd-897e-473f-ba00-011d4005aed6",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Процессор AMD soc-AM4 A8-9600 OEM 4\/4 Cores (3.1GHz,3.4GHz Max\/2Mb\/28nm) Radeon R7 int. 65W",
                    "code": "255",
                    "barCodes": [
                        "2000000000060"
                    ],
                    "price": 3590,
                    "costPrice": 2694,
                    "quantity": 2,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "822455cf-20a1-42ec-ad9d-4c548f1cc08f",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "20eb13d6-c261-4cec-b18a-7ac32420a324",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Процессор Intel soc-1151v2 Pentium G5400 OEM 2\/4 Cores (3.7GHz\/4Mb\/14nm\/DMI) UHD Graphics 610 int., 65W",
                    "code": "254",
                    "barCodes": [
                        "2000000000053"
                    ],
                    "price": 5800,
                    "costPrice": 5063,
                    "quantity": 0,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "822455cf-20a1-42ec-ad9d-4c548f1cc08f",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "210a4a92-abf2-4b3a-9082-577064fad451",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Процессор AMD soc-AM4 Athlon X4 950 OEM 4\/4 Cores (3.5GHz\/3.8GHz Max\/2Mb\/28nm) no Video 65W",
                    "code": "256",
                    "barCodes": [
                        "2000000000077"
                    ],
                    "price": 2690,
                    "costPrice": 2740,
                    "quantity": 1,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "822455cf-20a1-42ec-ad9d-4c548f1cc08f",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "a54514e0-f568-417b-8f9b-56fbd8a89468",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Процессор AMD soc-AM4 Athlon 200GE 2\/4 core (3.2GHz\/4Mb\/14nm) Radeon Vega 3 35W",
                    "code": "181",
                    "barCodes": [
                        "730143309325"
                    ],
                    "price": 2950,
                    "costPrice": 2731,
                    "quantity": 0,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "822455cf-20a1-42ec-ad9d-4c548f1cc08f",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "0f1ca25f-4af2-473f-88bd-395550212720",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Процессор AMD soc-AM4 Ryzen 3 2200G OEM 4\/4 Cores (3.5GHz\/3.7GHz\/4Mb\/14nm) Vega 8 int.65W",
                    "code": "302",
                    "barCodes": [
                        "2000000000091"
                    ],
                    "price": 6190,
                    "costPrice": 5877,
                    "quantity": 0,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "822455cf-20a1-42ec-ad9d-4c548f1cc08f",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "b01ae616-e864-4322-a4c0-c43af07130c1",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Процессор AMD soc-AM3+ FX-6300 OEM 6\/6 Cores 95W",
                    "code": "587",
                    "barCodes": [
                        "2000000000312"
                    ],
                    "price": 3090,
                    "costPrice": 2834,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "822455cf-20a1-42ec-ad9d-4c548f1cc08f",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "6514427e-d7dd-467e-9f75-02ec4ba8d339",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Блок питания AeroCool 500W ECO-500 120mm v2.3 1.35кг",
                    "code": "612",
                    "barCodes": [
                        "4710700957882"
                    ],
                    "price": 1799,
                    "costPrice": 1621,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "a47216aa-f058-40ef-9725-9eea7fd99bc1",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "a69ce237-7fe7-48d7-ab01-28839fd4dc43",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Блок питания Aerocool 450W ECO-450 120mm V2.3 1.35 кг",
                    "code": "213",
                    "barCodes": [
                        "4710700957875"
                    ],
                    "price": 1750,
                    "costPrice": 1500,
                    "quantity": 1,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "a47216aa-f058-40ef-9725-9eea7fd99bc1",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "5ae5942e-629c-4184-8485-c62cc8f9b33b",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Блок питания Aerocool ATX 700W VX PLUS 700W (24+4+4pin) APFC 120mm fan 4xSATA RTL",
                    "code": "613",
                    "barCodes": [
                        "4713105962796"
                    ],
                    "price": 3150,
                    "costPrice": 2990,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "a47216aa-f058-40ef-9725-9eea7fd99bc1",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "9829bdf2-a51e-4a81-b958-920476a01531",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Память DDR4 8Gb Hynix 3rd 2400Mhz (PC2400)",
                    "code": "639",
                    "barCodes": [
                        "758182667299"
                    ],
                    "price": 2850,
                    "costPrice": 2312,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "f8c2581b-d146-4885-9aee-681e4d3614b7",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "77798f96-9ed8-4bc3-b60d-21a6546a99e9",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Корпус Zalman ZM-T2 Plus, без БП, mATX",
                    "code": "42",
                    "barCodes": [
                        "8809213766084"
                    ],
                    "price": 2200,
                    "costPrice": 1647,
                    "quantity": 0,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "e8d08c80-2c51-4cc5-b25f-a2f993a0079f",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "9305d5a3-0f6d-49b6-9875-ddbb82854660",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Корпус ZALMAN ZM-T3, w\/o PSU, black",
                    "code": "44",
                    "barCodes": [
                        "8809213765773"
                    ],
                    "price": 2200,
                    "costPrice": 1754,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "e8d08c80-2c51-4cc5-b25f-a2f993a0079f",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "f603c6c4-537a-4686-a048-612847542fd2",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Корпус Zalman ZM-T5 Plus, без БП, mATX",
                    "code": "519",
                    "barCodes": [
                        "8809213767203",
                        "823884207026",
                        "4537694163354"
                    ],
                    "price": 2200,
                    "costPrice": 1703,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "e8d08c80-2c51-4cc5-b25f-a2f993a0079f",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "8cd9462c-3877-442f-9de3-d57a5e20bbb4",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Память DDR2 2Gb Hynix 3rd 800Mhz (PC6400)",
                    "code": "656",
                    "barCodes": [
                        "GE107190809GE"
                    ],
                    "price": 1000,
                    "costPrice": 835,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "f8c2581b-d146-4885-9aee-681e4d3614b7",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "c26bff23-ce60-478a-9d6e-900a056df866",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Память DDR4 4Gb Crucial 2666MHz PC4-21300 CT4G4DFS8266 CL19 RTL",
                    "code": "657",
                    "barCodes": [
                        "649528785930"
                    ],
                    "price": 1599,
                    "costPrice": 1499,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "f8c2581b-d146-4885-9aee-681e4d3614b7",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "3029fff7-6a1f-4d8f-a15f-aaaa8d98c25b",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Кабель-удлинитель USB 2.0 1.8m CableExpert (CCP-USB2-AMAF-6) позолоч. контакты",
                    "code": "333",
                    "barCodes": [
                        "8716309041881"
                    ],
                    "price": 100,
                    "costPrice": 60,
                    "quantity": 2,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "b881b484-85c3-4770-a158-4d0bc06cd417",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "7425ca59-59b5-4fab-b10f-3e0de7378f9f",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Кабель USB 2,0 Am-Bm 1,8м для принтера",
                    "code": "661",
                    "barCodes": [
                        "8716309091091"
                    ],
                    "price": 150,
                    "costPrice": 82,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "b881b484-85c3-4770-a158-4d0bc06cd417",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "ef0caddc-fd89-490a-a7ca-dd9eedafa61e",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Кабель Smartbuy USB - 30-pin для Apple, нейлон, длина 1,2 м (iK-412n)",
                    "code": "662",
                    "barCodes": [
                        "4690626024250",
                        "4690626024267"
                    ],
                    "price": 100,
                    "costPrice": 56,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "b881b484-85c3-4770-a158-4d0bc06cd417",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "1c3ef018-109c-40fe-95c9-7c0f20bd457a",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Накопитель SSD  2.5\" 240Gb Kingston A400 SA400S37\/240G SATA III 2.5\" 7mm R:500Mb\/s W:350Mb\/s TLC",
                    "code": "468",
                    "barCodes": [
                        "740617261219"
                    ],
                    "price": 2499,
                    "costPrice": 2363,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "5aee69ad-1670-4fa5-a103-9a79171a7032",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "1f8da906-2f31-4847-b735-28e34da76012",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Жесткий диск WD Caviar Blue WD10EZEX, 1Тб, SATA III, 3.5\"",
                    "code": "30",
                    "barCodes": [
                        "WD10EZEX-08WN4A0"
                    ],
                    "price": 2999,
                    "costPrice": 2749,
                    "quantity": 2,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "5aee69ad-1670-4fa5-a103-9a79171a7032",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "a5b67ea7-5708-4688-88c4-c3f4b2682d68",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Накопитель SSD M.2 128Gb SmartBuy (SBSSD-128GT-PH08T-M2P2) 3D TLC",
                    "code": "666",
                    "barCodes": [
                        "4690626042742"
                    ],
                    "price": 1799,
                    "costPrice": 1630,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "5aee69ad-1670-4fa5-a103-9a79171a7032",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "4db06c7f-50d8-4d33-a9ed-75a7c66768f3",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Беспроводной адаптер TP-LINK TL-WN881ND PCI-E 802.11b\/g. до 300Mbps",
                    "code": "667",
                    "barCodes": [
                        "6935364050573"
                    ],
                    "price": 930,
                    "costPrice": 818,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "eb76eb70-0576-4b7a-b0b0-bb6ede202e84",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "72c2c57c-38dd-42d9-9368-494bce23b607",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Накопитель SSD 2.5\" 480Gb A-Data Ultimate SU630SS ASU630SS-480GQ-R SATA III",
                    "code": "507",
                    "barCodes": [
                        "4713218469182"
                    ],
                    "price": 3850,
                    "costPrice": 3230,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "5aee69ad-1670-4fa5-a103-9a79171a7032",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "1090d6fb-e963-4fc6-93c8-21fd13e83f26",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Вентилятор 5bites F12025S-2 120x120x25 sleeve 1200RPM 25dBa 2pin",
                    "code": "680",
                    "barCodes": [
                        "4710871004866"
                    ],
                    "price": 220,
                    "costPrice": 138,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "0a4d7614-5480-4d7b-9ed2-705d8e03f8b6",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "1c47b9ef-93d1-4c4e-b55e-533397c76476",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Кабель аудио 0.1м 3.5jack\/M-2*3.5jack\/F Cablexpert CCA-415-0.1M",
                    "code": "681",
                    "barCodes": [
                        "8716309096942"
                    ],
                    "price": 100,
                    "costPrice": 49,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "b881b484-85c3-4770-a158-4d0bc06cd417",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "408e4137-7267-440f-b9b5-cad1f2eb54e1",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Адаптер HDMI F-DVI M, Cablexpert",
                    "code": "38",
                    "barCodes": [
                        "8716309054836"
                    ],
                    "price": 150,
                    "costPrice": 96,
                    "quantity": 1,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "b881b484-85c3-4770-a158-4d0bc06cd417",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "c90fa453-5809-428e-bfaf-9649b06ee334",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Вентилятор PCCooler S88 универсальный (TDP 98W, 1200-2000RPM, 20.5 dB) Al PWM",
                    "code": "475",
                    "barCodes": [
                        "6940526110804"
                    ],
                    "price": 990,
                    "costPrice": 671,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "0a4d7614-5480-4d7b-9ed2-705d8e03f8b6",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "1b03f152-8841-4110-95ad-ef22c50b38d8",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Вентилятор PCCooler S83 TDP 90W",
                    "code": "251",
                    "barCodes": [
                        "6940526110811"
                    ],
                    "price": 900,
                    "costPrice": 520,
                    "quantity": 1,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "0a4d7614-5480-4d7b-9ed2-705d8e03f8b6",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "297981c7-0432-40e0-80f0-707d7c73f306",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Кабель Cableexpert CCA-404 Jack 3,5 mm - Jack 3,5 mm, 1,2 м ",
                    "code": "497",
                    "barCodes": [
                        "8716309024570"
                    ],
                    "price": 50,
                    "costPrice": 32,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "b881b484-85c3-4770-a158-4d0bc06cd417",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "cd2f2b2c-838e-441d-b356-0183901f498b",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Адаптер DVI - VGA Smartbuy (A-123)",
                    "code": "555",
                    "barCodes": [
                        "4690626023673"
                    ],
                    "price": 150,
                    "costPrice": 51,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": null,
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "2c7d81e6-80cd-46d2-af38-e1807fcd0463",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Привод DVD+RW LG Slim GUB0N\/GUD0N 9,5мм",
                    "code": "684",
                    "barCodes": [
                        "2000000000343"
                    ],
                    "price": 1100,
                    "costPrice": 986,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "cc6215ca-b114-448e-96be-9568dca27301",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "5d4d0cc0-6555-4472-91ed-40ab95de9f17",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Накопитель SSD 2.5\" 240Gb Smartbuy Revival 3 (SB240Gb-RVVL3-25SAT3) 3D NAND",
                    "code": "542",
                    "barCodes": [
                        "4690626011281"
                    ],
                    "price": 2300,
                    "costPrice": 1999,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "5aee69ad-1670-4fa5-a103-9a79171a7032",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "7465081e-152f-4db6-a43c-3e382134420b",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Жесткий диск Seagate Barracuda ST1000DM010, 1Tb, SATA III, 3.5\"",
                    "code": "110",
                    "barCodes": [
                        "ST1000DM010"
                    ],
                    "price": 2999,
                    "costPrice": 2650,
                    "quantity": 1,
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "5aee69ad-1670-4fa5-a103-9a79171a7032",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "1f52b876-d043-4b34-a785-98551f925f86",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Жесткий диск SSD Smartbuy 120GB Revival3 SATA3",
                    "code": "685",
                    "barCodes": [
                        "4690626011274"
                    ],
                    "price": 1450,
                    "costPrice": 1332,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "5aee69ad-1670-4fa5-a103-9a79171a7032",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "ac5490dd-8b46-4933-ad3a-9a5f29b22b55",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Память DDR2 2Gb Hynix 3rd 800Mhz (PC6400)",
                    "code": "686",
                    "barCodes": [
                        "HYMP125U64CP8-S6  AB-C"
                    ],
                    "price": 1200,
                    "costPrice": 843,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "f8c2581b-d146-4885-9aee-681e4d3614b7",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                },
                {
                    "uuid": "b1ce29ea-f318-45a3-a9ec-985d4a208fa5",
                    "group": false,
                    "hasVariants": false,
                    "type": "NORMAL",
                    "name": "Память SO DDR3 8Gb Patriot 1333Mhz PC10600 CL9",
                    "code": "560",
                    "barCodes": [
                        "815530012092"
                    ],
                    "price": 2790,
                    "costPrice": 2500,
                    "quantity": "0.000",
                    "measureName": "шт",
                    "tax": "NO_VAT",
                    "allowToSell": true,
                    "description": "",
                    "articleNumber": "",
                    "parentUuid": "f8c2581b-d146-4885-9aee-681e4d3614b7",
                    "alcoCodes": null,
                    "alcoholByVolume": null,
                    "alcoholProductKindCode": null,
                    "tareVolume": null
                }
            ],
    };


    async getResource(url) {
        //const body = JSON.stringify(data);
        const headers = new Headers({
            'Content-Type': 'application/json;charset=utf-8',
            'X-Authorization': this.state.token,
        });

        // https://api.evotor.ru/api/v1/inventories/stores/search
        const response = await fetch(`${this._apiEvotorBase}/${url}`, {
            method: 'GET',
            headers: headers
        });

        if(!response.ok){
            throw new Error(`Could not fetch ${url}, received ${response.status}`)
        }
        return await response.json();
    }

    async getAllStores(){
        this.state = await this.getResource(`inventories/stores/search`);
        return this.state
    }

    async getAllEmployees(){
        return await this.getResource(`inventories/employees/search`)
    }

    async getAllProducts(store_id){
        return new Promise (resolve=>{
         setTimeout(() => {
          resolve(this.state.data);
      }, 1000);
        });
    }

    //async getAllProducts(store_id){
    //    return await this.getResource(`inventories/stores/${this.state.stores[store_id].uuid}/products`)
    //}
}